create schema skablemain;

CREATE TABLE bill_mail_list (id INT NOT NULL AUTO_INCREMENT, bill_mail_id VARCHAR(100), PRIMARY KEY (id));
CREATE TABLE branchmst (branch_cd BIGINT NOT NULL AUTO_INCREMENT, branch_name VARCHAR(255) NOT NULL, sh_name VARCHAR(2), address1 VARCHAR(255), address2 VARCHAR(255), address3 VARCHAR(255), email VARCHAR(255), phone VARCHAR(255), cash_ac_cd VARCHAR(7), ins_amt DECIMAL(10, 2) DEFAULT 0.00 , PRIMARY KEY (branch_cd));
CREATE TABLE dbmst (CMP_NAME VARCHAR(50) NOT NULL, DB_YEAR VARCHAR(4) NOT NULL, DB_NAME VARCHAR(25) NOT NULL, PRIMARY KEY (CMP_NAME, DB_YEAR));
CREATE TABLE formmst (FORM_CD BIGINT NOT NULL AUTO_INCREMENT, FORM_NAME VARCHAR(255), MENU_CD BIGINT, PRIMARY KEY (FORM_CD));
CREATE TABLE menumst (MENU_CD BIGINT NOT NULL AUTO_INCREMENT, MENU_NAME VARCHAR(255), PRIMARY KEY (MENU_CD));
CREATE TABLE system_variables (id BIGINT NOT NULL AUTO_INCREMENT, PARAM_NAME VARCHAR(50), PARAM_VALUE VARCHAR(255), PRIMARY KEY (id));
CREATE TABLE user_grp_mst (USER_GRP_CD BIGINT NOT NULL AUTO_INCREMENT, USER_GRP VARCHAR(255), PRIMARY KEY (USER_GRP_CD));
CREATE TABLE user_rights (USER_GRP_CD BIGINT, FORM_CD BIGINT, VIEWS DECIMAL(1) DEFAULT 0 , ADDS DECIMAL(1) DEFAULT 0 , EDITS DECIMAL(1) DEFAULT 0 , DELETES DECIMAL(1) DEFAULT 0 , PRINTS DECIMAL(1) DEFAULT 0 );
CREATE TABLE usermst (USER_ID DECIMAL(2) NOT NULL, USER_NAME VARCHAR(100), PASSWORD VARCHAR(32), EMAIL_ID VARCHAR(100), IS_ACTIVE DECIMAL(1) DEFAULT 1 , USER_GRP_CD BIGINT DEFAULT 0 , BRANCH_CD BIGINT DEFAULT 0 , PRIMARY KEY (USER_ID));

INSERT INTO system_variables (PARAM_NAME, PARAM_VALUE) VALUES ('SMS_KEY', 'A0f090bc3b9c8b12064bf219df4681c64');
INSERT INTO system_variables (PARAM_NAME, PARAM_VALUE) VALUES ('SMS_SENDER', 'iPearl');
INSERT INTO system_variables (PARAM_NAME, PARAM_VALUE) VALUES ('BILL_MAIL_ID', 'bill.ipearl@gmail.com');
INSERT INTO system_variables (PARAM_NAME, PARAM_VALUE) VALUES ('BILL_MAIL_PASSWORD', 'billipearl');

INSERT INTO user_grp_mst (USER_GRP) VALUES ('ADMIN');

INSERT INTO menumst (MENU_NAME) VALUES ('MASTER');
INSERT INTO menumst (MENU_NAME) VALUES ('TRANSACTION');
INSERT INTO menumst (MENU_NAME) VALUES ('INVENTORY');
INSERT INTO menumst (MENU_NAME) VALUES ('ACCOUNTS');
INSERT INTO menumst (MENU_NAME) VALUES ('UTILITY');

INSERT INTO usermst (USER_ID, USER_NAME, PASSWORD, EMAIL_ID, IS_ACTIVE, USER_GRP_CD, BRANCH_CD) VALUES (1, '', '', '', 1, 1, 0);

INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('GROUP MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('ACCOUNT MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BRAND MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('MODEL MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('COLOR MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('MEMORY MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SERIES MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TAX MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('RD PURCHASE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('URD PURCHASE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE RETURN', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('RETAIL INVOICE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TAX INVOICE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES RETURN', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES INVOICE BY NUMBER', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CASH PAYMENT', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CASH RECEIPT', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BANK PAYMENT', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BANK RECEIPT', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('JOURNAL ENTRY', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CONTRA ENTRY', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK TRANSFER', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('DC ISSUE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK ADJUSTMENT', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CREDIT NOTE ITEM LIST', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK LEDGER', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK LEDGER RATE', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK ITEMWISE MONTHWISE', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK SUMMARY', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK SUMMARY BALANCE', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK STATEMENT IMEI', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK VALUE STATEMENT IMEI', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK STATEMENT ACCESSSORY', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK VALUE STATEMENT ACCESSORY', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK VALUE STATEMENT DATE WISE', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK STATEMENT DATE WISE', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TAG TRACK TRANSACTIONWISE', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES REGISTER DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES REGISTER ACCOUNT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('INSURANCE REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE REGISTER DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE REGISTER DETAIL ACCOUNT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES RETURN REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES RETURN REGISTER DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES RETURN REGISTER DETAIL ACCOUNT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE RETURN REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE RETURN REGISTER DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURHASE RETURN REGISTER DETAIL ACCOUNT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BUY BACK REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('DC REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CREDIT NOTE REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK ADJUSTMENT REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES REGISTER CARD WISE', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES REGISTER CARD WISE DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('GENERAL LEDGER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('GROUP SUMMARY', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CASH BOOK', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BANK BOOK', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('DAILY SALES STATEMENT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('DAILY SALES STATEMENT DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE WISE SALES STATEMENT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE WISE SALES STATEMENT DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE WISE PURCHASE STATEMENT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE WISE PURCHASE STATEMENT DETAIL', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('MARGIN REPORT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('MARGIN REPORT BY TAG', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('IMEI PS ON PURCHASE', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('IMEI PS ON SALES', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE WISE PROFIT STATEMENT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE WISE BRAND WISE PROFIT STATEMENT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('IMEI SEARCH', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TAG TRACK', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CREATE USER', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('DUMMY PRINT', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('UPDATE USER', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('USER RIGHTS', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('USER GROUP MASTER', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('IN TRANSIT REPORT', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK IN OUT REPORT', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE PARTY WISE ONLY CODE', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE RATE BY TAG', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SNAP SHOT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALESMAN MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('REFRAL MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCHASE BILL .', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('RETAIL INVOICE .', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('CREDIT NOTE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('DEBIT NOTE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('ORDER BOOK', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BRAND WISE ITEM LEDGER', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('DATE WISE STOCK ON HAND', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('ITEMWISE DATE/MONTH WISE PURCHASE STATEMENT', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('ITEMWISE DATE/MONTH WISE SALES STATEMENT', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('MODELWISE MONTHWISE PURCHASE STATEMENT', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('MODELWISE MONTHWISE SALES STATEMENT', 3);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BRANCHWISE PENDING COLLECTION REPORT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TAX REPORT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('JOURNAL REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('OPENING BALANCE REGISTER', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TYPE WISE SALES WITHOUT TAG', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('AVERAGE PURCHASE REPORT', 4);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PHONE BOOK', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PHONE BOOK VIEW', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('EOD', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BUY BACK TRACK', 5);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SCHEME MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('TID MASTER', 1);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BILL ADJUSTMENT', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('STOCK TRANSFER BRANCH', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('VISITOR BOOK', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('QUOTATION', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('BRANCH WISE INSURANCE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('RD PURCHASE LOCAL', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('RD PURCAHSE OUTSIDE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCAHSE RETURN LOCAL', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('PURCAHSE RETURN OUTSIDE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES INVOICE LOCAL', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES INVOICE OUTSIDE', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES RETURN LOCAL', 2);
INSERT INTO formmst (FORM_NAME, MENU_CD) VALUES ('SALES RETURN OUTSIDE', 2);

INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 1, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 2, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 3, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 4, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 5, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 6, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 7, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 8, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 9, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 10, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 11, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 12, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 13, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 14, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 15, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 16, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 17, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 18, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 19, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 20, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 21, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 22, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 23, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 24, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 25, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 26, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 27, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 28, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 29, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 30, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 31, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 32, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 33, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 34, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 35, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 36, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 37, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 38, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 39, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 40, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 41, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 42, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 43, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 44, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 45, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 46, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 47, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 48, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 49, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 50, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 51, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 52, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 53, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 54, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 55, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 56, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 57, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 58, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 59, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 60, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 61, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 62, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 63, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 64, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 65, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 66, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 67, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 68, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 69, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 70, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 71, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 72, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 73, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 74, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 75, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 76, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 77, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 78, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 79, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 80, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 86, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 87, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 88, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 89, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 91, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 91, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 92, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 93, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 94, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 95, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 96, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 97, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 98, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 99, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 101, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 101, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 102, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 103, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 104, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 105, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 106, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 107, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 108, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 98, 1, 1, 1, 1, 1);
INSERT INTO user_rights (USER_GRP_CD, FORM_CD, VIEWS, ADDS, EDITS, DELETES, PRINTS) VALUES (1, 90, 1, 1, 1, 1, 1);


CREATE schema skablelogindb;
CREATE TABLE company_mst (AC_YEAR VARCHAR(4) NOT NULL, CMPN_NAME VARCHAR(100) NOT NULL, ADDRESS1 VARCHAR(255), ADDRESS2 VARCHAR(255), ADDRESS3 VARCHAR(255), CITY VARCHAR(50), PINCODE VARCHAR(6), PHONE_NO VARCHAR(15), FAX_NO VARCHAR(15), CST_NO VARCHAR(20), TIN_NO VARCHAR(20), PAN_NO VARCHAR(10), SH_NAME VARCHAR(2), EMAILID VARCHAR(100), CASH_AC_CD VARCHAR(7), KASAR_AC VARCHAR(7), COUNTRY VARCHAR(10), PROVIANCE VARCHAR(25), PURCHASE_AC VARCHAR(7), SALES_AC VARCHAR(7), PURCHASE_RETURN_AC VARCHAR(7), SALES_RETURN_AC VARCHAR(7), BUY_BACK_AC VARCHAR(7), URD_PURCHASE VARCHAR(7), DISC_AC VARCHAR(7), gst_no VARCHAR(50), PRIMARY KEY (AC_YEAR, CMPN_NAME));


create schema skable2017;
-- MySQL dump 10.13  Distrib 5.7.12, for osx10.9 (x86_64)
--
-- Host: 127.0.0.1    Database: ipearl0117
-- ------------------------------------------------------
-- Server version	5.7.17

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `acntmst`
--

DROP TABLE IF EXISTS `acntmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `acntmst` (
  `AC_CD` varchar(7) NOT NULL,
  `FNAME` varchar(100) NOT NULL,
  `MNAME` varchar(50) NOT NULL,
  `LNAME` varchar(25) NOT NULL,
  `GRP_CD` varchar(7) NOT NULL,
  `CONTACT_PRSN` varchar(255) NOT NULL,
  `CST` varchar(50) NOT NULL,
  `PAN` varchar(50) NOT NULL,
  `REF_BY` varchar(255) NOT NULL,
  `EDIT_NO` int(11) NOT NULL DEFAULT '0',
  `USER_ID` int(11) NOT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `AC_ALIAS` varchar(5) DEFAULT NULL,
  `TIN` varchar(20) DEFAULT NULL,
  `CARD_NO` varchar(16) DEFAULT NULL,
  `OPB_AMT` decimal(10,2) DEFAULT '0.00',
  `OPB_EFF` decimal(1,0) DEFAULT '0',
  `REF_AC_CD` varchar(7) DEFAULT NULL,
  `gst_no` varchar(50) DEFAULT '',
  PRIMARY KEY (`AC_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `adbkmst`
--

DROP TABLE IF EXISTS `adbkmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `adbkmst` (
  `AC_CD` varchar(7) NOT NULL,
  `ADD1` varchar(255) NOT NULL,
  `ADD2` varchar(255) NOT NULL,
  `ADD3` varchar(255) NOT NULL,
  `AREA_CD` int(11) NOT NULL,
  `CITY_CD` int(11) NOT NULL,
  `sr_no` decimal(2,0) NOT NULL,
  PRIMARY KEY (`AC_CD`,`sr_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `billadjst`
--

DROP TABLE IF EXISTS `billadjst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `billadjst` (
  `doc_ref_no` varchar(7) NOT NULL,
  `DR_DOC_REF_NO` varchar(7) DEFAULT NULL,
  `CR_DOC_REF_NO` varchar(7) DEFAULT NULL,
  `DR_DOC_CD` varchar(5) DEFAULT NULL,
  `CR_DOC_CD` varchar(7) DEFAULT NULL,
  `DR_INV_NO` int(11) DEFAULT NULL,
  `CR_INV_NO` int(11) DEFAULT NULL,
  `AMT` decimal(10,2) DEFAULT '0.00',
  `DR_SR_NO` decimal(2,0) DEFAULT '1',
  `CR_SR_NO` decimal(2,0) DEFAULT '1',
  `ac_cd` varchar(7) DEFAULT NULL,
  `is_type` decimal(1,0) DEFAULT '0',
  PRIMARY KEY (`doc_ref_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bprdt`
--

DROP TABLE IF EXISTS `bprdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bprdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `DOC_REF_NO` varchar(7) DEFAULT NULL,
  `BAL` decimal(10,2) DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `bprhd`
--

DROP TABLE IF EXISTS `bprhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `bprhd` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `TOT_BAL` decimal(10,2) DEFAULT '0.00',
  `AC_CD` varchar(7) DEFAULT NULL,
  `BANK_CD` varchar(7) DEFAULT NULL,
  `CHEQUE_NO` varchar(255) DEFAULT NULL,
  `CHEQUE_DATE` date DEFAULT NULL,
  `CTYPE` decimal(1,0) DEFAULT NULL,
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_cd` decimal(2,0) DEFAULT '0',
  `OPP_BANK_NAME` varchar(255) DEFAULT NULL,
  `rec_date` date DEFAULT NULL,
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `brandmst`
--

DROP TABLE IF EXISTS `brandmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `brandmst` (
  `BRAND_CD` varchar(7) NOT NULL,
  `BRAND_NAME` varchar(50) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BRAND_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `colourmst`
--

DROP TABLE IF EXISTS `colourmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `colourmst` (
  `COLOUR_CD` varchar(7) NOT NULL,
  `COLOUR_NAME` varchar(50) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`COLOUR_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `contradt`
--

DROP TABLE IF EXISTS `contradt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `contradt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` int(11) NOT NULL,
  `AC_CD` varchar(7) NOT NULL,
  `AMT` decimal(15,5) NOT NULL,
  `DRCR` int(11) NOT NULL,
  `PART` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `contrahd`
--

DROP TABLE IF EXISTS `contrahd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `contrahd` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `DR` decimal(15,5) NOT NULL,
  `CR` decimal(15,5) NOT NULL,
  `IS_DEL` int(11) DEFAULT '0',
  `PRN_NO` int(11) DEFAULT '0',
  `USER_ID` int(11) NOT NULL,
  `EDIT_NO` int(11) NOT NULL DEFAULT '0',
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REMARK` varchar(255) DEFAULT NULL,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `branch_cd` decimal(3,0) DEFAULT NULL,
  `rec_date` date DEFAULT NULL,
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cprdt`
--

DROP TABLE IF EXISTS `cprdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cprdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `DOC_REF_NO` varchar(7) DEFAULT NULL,
  `BAL` decimal(10,2) DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `cprhd`
--

DROP TABLE IF EXISTS `cprhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `cprhd` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `TOT_BAL` decimal(10,2) DEFAULT '0.00',
  `AC_CD` varchar(7) DEFAULT NULL,
  `CTYPE` decimal(1,0) DEFAULT NULL,
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_cd` decimal(2,0) DEFAULT '0',
  `cash_ac_cd` varchar(7) DEFAULT 'A000001',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `dcdt`
--

DROP TABLE IF EXISTS `dcdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `dcdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `RATE` decimal(10,2) DEFAULT '0.00',
  `AMT` decimal(10,2) DEFAULT '0.00',
  `PUR_TAG_NO` varchar(7) DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  `sr_name` varchar(255) DEFAULT '',
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `dchd`
--

DROP TABLE IF EXISTS `dchd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `dchd` (
  `REF_NO` varchar(7) NOT NULL,
  `INV_NO` int(11) DEFAULT NULL,
  `V_DATE` date DEFAULT NULL,
  `V_TYPE` decimal(1,0) DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `DET_TOT` decimal(10,2) DEFAULT '0.00',
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_cd` decimal(3,0) DEFAULT '1',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `denomation`
--

DROP TABLE IF EXISTS `denomation`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `denomation` (
  `v_date` date NOT NULL,
  `branch_cd` decimal(3,0) NOT NULL DEFAULT '0',
  `note_cd` decimal(1,0) NOT NULL DEFAULT '0',
  `qty` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`v_date`,`branch_cd`,`note_cd`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `dncndt`
--

DROP TABLE IF EXISTS `dncndt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `dncndt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `DOC_REF_NO` varchar(7) DEFAULT NULL,
  `BAL` decimal(10,2) DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `dncnhd`
--

DROP TABLE IF EXISTS `dncnhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `dncnhd` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `TOT_BAL` decimal(10,2) DEFAULT '0.00',
  `AC_CD` varchar(7) DEFAULT NULL,
  `BANK_CD` varchar(7) DEFAULT NULL,
  `CTYPE` decimal(1,0) DEFAULT NULL,
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_cd` decimal(2,0) DEFAULT '0',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `groupmst`
--

DROP TABLE IF EXISTS `groupmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `groupmst` (
  `GRP_CD` varchar(7) NOT NULL,
  `GROUP_NAME` varchar(50) NOT NULL,
  `HEAD` decimal(5,0) DEFAULT '0',
  `HEAD_GRP` varchar(7) DEFAULT NULL,
  `ACC_EFF` int(11) DEFAULT NULL,
  `SIDE` int(11) DEFAULT '2',
  `EDIT_NO` smallint(6) DEFAULT '0',
  `USER_ID` int(11) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`GRP_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jvdt`
--

DROP TABLE IF EXISTS `jvdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jvdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` int(11) NOT NULL,
  `AC_CD` varchar(7) NOT NULL,
  `AMT` decimal(15,5) NOT NULL,
  `DRCR` int(11) NOT NULL,
  `PART` varchar(255) DEFAULT NULL,
  `imei` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `jvhd`
--

DROP TABLE IF EXISTS `jvhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `jvhd` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `DR` decimal(15,5) NOT NULL,
  `CR` decimal(15,5) NOT NULL,
  `IS_DEL` int(11) DEFAULT '0',
  `PRN_NO` int(11) DEFAULT '0',
  `USER_ID` int(11) NOT NULL,
  `EDIT_NO` int(11) NOT NULL DEFAULT '0',
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REMARK` varchar(255) DEFAULT NULL,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `branch_cd` decimal(3,0) DEFAULT NULL,
  `rec_date` date DEFAULT NULL,
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lbrpdt`
--

DROP TABLE IF EXISTS `lbrpdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lbrpdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(4,0) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `RATE` decimal(10,2) DEFAULT '0.00',
  `TAX_CD` varchar(7) DEFAULT NULL,
  `BASIC_AMT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `AMT` decimal(10,2) DEFAULT '0.00',
  `PUR_TAG_NO` varchar(7) DEFAULT NULL,
  `DISC_RATE` decimal(10,2) DEFAULT '0.00',
  `MRP` decimal(10,2) DEFAULT '0.00',
  `IS_MAIN` decimal(1,0) DEFAULT '1',
  `nlc` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `lbrphd`
--

DROP TABLE IF EXISTS `lbrphd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `lbrphd` (
  `REF_NO` varchar(7) NOT NULL,
  `INV_NO` int(11) DEFAULT NULL,
  `V_DATE` date DEFAULT NULL,
  `DUE_DATE` date DEFAULT NULL,
  `V_TYPE` decimal(1,0) DEFAULT NULL,
  `PMT_MODE` decimal(1,0) DEFAULT NULL,
  `BILL_DATE` date DEFAULT NULL,
  `BILL_NO` varchar(50) DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `DET_TOT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADJST` decimal(10,2) DEFAULT '0.00',
  `REMARK` varchar(255) DEFAULT NULL,
  `FR_CHG` decimal(10,2) DEFAULT '0.00',
  `NET_AMT` decimal(10,2) DEFAULT '0.00',
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `BRANCH_CD` int(11) DEFAULT NULL,
  `scheme_cd` varchar(7) DEFAULT NULL,
  `tax_type` decimal(1,0) DEFAULT '0',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `memorymst`
--

DROP TABLE IF EXISTS `memorymst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `memorymst` (
  `MEMORY_CD` varchar(7) NOT NULL,
  `MEMORY_NAME` varchar(20) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MEMORY_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `modelmst`
--

DROP TABLE IF EXISTS `modelmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `modelmst` (
  `MODEL_CD` varchar(7) NOT NULL,
  `MODEL_NAME` varchar(150) DEFAULT NULL,
  `BRAND_CD` varchar(7) DEFAULT NULL,
  `TAX_CD` varchar(7) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TYPE_CD` varchar(7) DEFAULT NULL,
  `sub_type_cd` varchar(7) DEFAULT NULL,
  `HSN_CODE` varchar(50) DEFAULT '',
  `gst_cd` varchar(7) DEFAULT '',
  PRIMARY KEY (`MODEL_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `notes`
--

DROP TABLE IF EXISTS `notes`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `notes` (
  `rec_no` bigint(20) NOT NULL AUTO_INCREMENT,
  `from_date` date DEFAULT NULL,
  `to_date` date DEFAULT NULL,
  `ac_cd` varchar(7) DEFAULT NULL,
  `descr` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`rec_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `odbdt`
--

DROP TABLE IF EXISTS `odbdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `odbdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `BAL` decimal(10,2) DEFAULT NULL,
  `REMARK` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `odbhd`
--

DROP TABLE IF EXISTS `odbhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `odbhd` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `TOT_BAL` decimal(10,2) DEFAULT '0.00',
  `AC_CD` varchar(7) DEFAULT NULL,
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `branch_cd` decimal(2,0) DEFAULT '0',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `oldb0_1`
--

DROP TABLE IF EXISTS `oldb0_1`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oldb0_1` (
  `REC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SR_CD` varchar(7) DEFAULT NULL,
  `BRANCH_CD` decimal(2,0) DEFAULT NULL,
  `PRD_ST_CD` decimal(1,0) DEFAULT NULL,
  `OPB` decimal(4,0) DEFAULT '0',
  `PPUR_4` decimal(4,0) DEFAULT '0',
  `PSAL_4` decimal(4,0) DEFAULT '0',
  `PPUR_5` decimal(4,0) DEFAULT '0',
  `PSAL_5` decimal(4,0) DEFAULT '0',
  `PPUR_6` decimal(4,0) DEFAULT '0',
  `PSAL_6` decimal(4,0) DEFAULT '0',
  `PPUR_7` decimal(4,0) DEFAULT '0',
  `PSAL_7` decimal(4,0) DEFAULT '0',
  `PPUR_8` decimal(4,0) DEFAULT '0',
  `PSAL_8` decimal(4,0) DEFAULT '0',
  `PPUR_9` decimal(4,0) DEFAULT '0',
  `PSAL_9` decimal(4,0) DEFAULT '0',
  `PPUR_10` decimal(4,0) DEFAULT '0',
  `PSAL_10` decimal(4,0) DEFAULT '0',
  `PPUR_11` decimal(4,0) DEFAULT '0',
  `PSAL_11` decimal(4,0) DEFAULT '0',
  `PPUR_12` decimal(4,0) DEFAULT '0',
  `PSAL_12` decimal(4,0) DEFAULT '0',
  `PPUR_1` decimal(4,0) DEFAULT '0',
  `PSAL_1` decimal(4,0) DEFAULT '0',
  `PPUR_2` decimal(4,0) DEFAULT '0',
  `PSAL_2` decimal(4,0) DEFAULT '0',
  `PPUR_3` decimal(4,0) DEFAULT '0',
  `PSAL_3` decimal(4,0) DEFAULT '0',
  PRIMARY KEY (`REC_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=2824 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `oldb0_2`
--

DROP TABLE IF EXISTS `oldb0_2`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oldb0_2` (
  `REC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `DOC_REF_NO` varchar(10) DEFAULT NULL,
  `DOC_CD` varchar(3) DEFAULT NULL,
  `INV_NO` int(11) DEFAULT '0',
  `DOC_DATE` date DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `BRANCH_CD` decimal(2,0) DEFAULT NULL,
  `PRD_ST_CD` decimal(1,0) DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `PCS` decimal(4,0) DEFAULT NULL,
  `TRNS_ID` varchar(1) DEFAULT NULL,
  `RATE` decimal(10,2) DEFAULT '0.00',
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `TAG_NO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`REC_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=164162 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `oldb2_1`
--

DROP TABLE IF EXISTS `oldb2_1`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oldb2_1` (
  `REC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `AC_CD` varchar(7) DEFAULT NULL,
  `OPB` decimal(10,2) DEFAULT '0.00',
  `DR_4` decimal(10,2) DEFAULT '0.00',
  `CR_4` decimal(10,2) DEFAULT '0.00',
  `DR_5` decimal(10,2) DEFAULT '0.00',
  `CR_5` decimal(10,2) DEFAULT '0.00',
  `DR_6` decimal(10,2) DEFAULT '0.00',
  `CR_6` decimal(10,2) DEFAULT '0.00',
  `DR_7` decimal(10,2) DEFAULT '0.00',
  `CR_7` decimal(10,2) DEFAULT '0.00',
  `DR_8` decimal(10,2) DEFAULT '0.00',
  `CR_8` decimal(10,2) DEFAULT '0.00',
  `DR_9` decimal(10,2) DEFAULT '0.00',
  `CR_9` decimal(10,2) DEFAULT '0.00',
  `DR_10` decimal(10,2) DEFAULT '0.00',
  `CR_10` decimal(10,2) DEFAULT '0.00',
  `DR_11` decimal(10,2) DEFAULT '0.00',
  `CR_11` decimal(10,2) DEFAULT '0.00',
  `DR_12` decimal(10,2) DEFAULT '0.00',
  `CR_12` decimal(10,2) DEFAULT '0.00',
  `DR_1` decimal(10,2) DEFAULT '0.00',
  `CR_1` decimal(10,2) DEFAULT '0.00',
  `DR_2` decimal(10,2) DEFAULT '0.00',
  `CR_2` decimal(10,2) DEFAULT '0.00',
  `DR_3` decimal(10,2) DEFAULT '0.00',
  `CR_3` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`REC_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=8030 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `oldb2_2`
--

DROP TABLE IF EXISTS `oldb2_2`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oldb2_2` (
  `REC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `DOC_REF_NO` varchar(7) DEFAULT NULL,
  `INV_NO` decimal(5,0) DEFAULT '0',
  `DOC_DATE` date DEFAULT NULL,
  `DOC_CD` varchar(3) DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `VAL` decimal(10,2) DEFAULT NULL,
  `CRDR` decimal(1,0) DEFAULT NULL,
  `PARTICULAR` varchar(255) DEFAULT NULL,
  `OPP_AC_CD` varchar(7) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REC_DATE` date DEFAULT NULL,
  `CHQ_NO` varchar(25) DEFAULT '',
  `REC_BANK_NAME` varchar(255) DEFAULT NULL,
  `BRANCH_CD` decimal(2,0) DEFAULT '0',
  PRIMARY KEY (`REC_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=237444 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `oldb2_3`
--

DROP TABLE IF EXISTS `oldb2_3`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oldb2_3` (
  `REC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `DOC_REF_NO` varchar(10) NOT NULL,
  `DOC_CD` varchar(3) DEFAULT NULL,
  `INV_NO` decimal(4,0) DEFAULT NULL,
  `DOC_DATE` date DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `TOT_AMT` decimal(13,2) DEFAULT '0.00',
  `UNPAID_AMT` decimal(13,2) DEFAULT '0.00',
  `DUE_DATE` date DEFAULT NULL,
  `CUR_ADJST` decimal(13,2) DEFAULT '0.00',
  PRIMARY KEY (`REC_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `oldb2_4`
--

DROP TABLE IF EXISTS `oldb2_4`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oldb2_4` (
  `REC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `DOC_REF_NO` varchar(10) NOT NULL,
  `DOC_CD` varchar(3) DEFAULT NULL,
  `INV_NO` decimal(4,0) DEFAULT NULL,
  `DOC_DATE` date DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `TOT_AMT` decimal(13,2) DEFAULT '0.00',
  `UNPAID_AMT` decimal(13,2) DEFAULT '0.00',
  `DUE_DATE` date DEFAULT NULL,
  `CUR_ADJST` decimal(13,2) DEFAULT '0.00',
  `SR_NO` decimal(2,0) DEFAULT '1',
  PRIMARY KEY (`REC_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=14364 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `opb_sr_val`
--

DROP TABLE IF EXISTS `opb_sr_val`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `opb_sr_val` (
  `SR_CD` varchar(7) NOT NULL,
  `SR_NO` smallint(6) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERIAL_NO` varchar(25) DEFAULT NULL,
  `P_RATE` decimal(10,2) DEFAULT '0.00',
  `BRANCH_CD` bigint(20) DEFAULT NULL,
  `REF_NO` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SR_CD`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `orderbook`
--

DROP TABLE IF EXISTS `orderbook`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `orderbook` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `amt` decimal(10,2) DEFAULT '0.00',
  `AC_CD` varchar(7) DEFAULT NULL,
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `model_cd` varchar(7) DEFAULT NULL,
  `memory_cd` varchar(7) DEFAULT NULL,
  `colour_cd` varchar(7) DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `edit_no` decimal(2,0) DEFAULT '0',
  `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `payment`
--

DROP TABLE IF EXISTS `payment`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `payment` (
  `REF_NO` varchar(7) DEFAULT NULL,
  `CASH_AMT` decimal(15,5) DEFAULT '0.00000',
  `BANK_CD` varchar(7) DEFAULT NULL,
  `BANK_NAME` varchar(255) DEFAULT NULL,
  `BANK_BRANCH` varchar(255) DEFAULT NULL,
  `CHEQUE_NO` varchar(50) DEFAULT NULL,
  `CHEQUE_DATE` date DEFAULT NULL,
  `BANK_AMT` decimal(15,5) DEFAULT '0.00000',
  `CARD_NAME` varchar(7) DEFAULT NULL,
  `CARD_AMT` decimal(15,5) DEFAULT '0.00000',
  `USER_ID` decimal(3,0) DEFAULT '1',
  `VOU_DATE` date DEFAULT NULL,
  `BAJAJ_AMT` decimal(10,2) DEFAULT '0.00',
  `BAJAJ_NAME` varchar(7) DEFAULT NULL,
  `SFID` varchar(25) DEFAULT NULL,
  `bajaj_per` decimal(10,2) DEFAULT '0.00',
  `bajaj_chg` decimal(10,2) DEFAULT '0.00',
  `card_per` decimal(10,2) DEFAULT '0.00',
  `card_chg` decimal(10,2) DEFAULT '0.00',
  `DISC_AMT` decimal(10,2) DEFAULT '0.00',
  `card_no` varchar(16) DEFAULT NULL,
  `tid_no` varchar(8) DEFAULT NULL,
  `cash_ac_cd` varchar(7) DEFAULT 'A000001'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `paymentlg`
--

DROP TABLE IF EXISTS `paymentlg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `paymentlg` (
  `REF_NO` varchar(7) DEFAULT NULL,
  `CASH_AMT` decimal(15,5) DEFAULT '0.00000',
  `BANK_CD` varchar(7) DEFAULT NULL,
  `BANK_NAME` varchar(255) DEFAULT NULL,
  `BANK_BRANCH` varchar(255) DEFAULT NULL,
  `CHEQUE_NO` varchar(50) DEFAULT NULL,
  `CHEQUE_DATE` date DEFAULT NULL,
  `BANK_AMT` decimal(15,5) DEFAULT '0.00000',
  `CARD_NAME` varchar(7) DEFAULT NULL,
  `CARD_AMT` decimal(15,5) DEFAULT '0.00000',
  `USER_ID` decimal(3,0) DEFAULT '1',
  `VOU_DATE` date DEFAULT NULL,
  `BAJAJ_AMT` decimal(10,2) DEFAULT '0.00',
  `BAJAJ_NAME` varchar(7) DEFAULT NULL,
  `SFID` varchar(25) DEFAULT NULL,
  `bajaj_per` decimal(10,2) DEFAULT '0.00',
  `bajaj_chg` decimal(10,2) DEFAULT '0.00',
  `card_per` decimal(10,2) DEFAULT '0.00',
  `card_chg` decimal(10,2) DEFAULT '0.00',
  `DISC_AMT` decimal(10,2) DEFAULT '0.00',
  `card_no` varchar(16) DEFAULT NULL,
  `tid_no` varchar(8) DEFAULT NULL,
  `cash_ac_cd` varchar(7) DEFAULT 'A000001'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `phbkmst`
--

DROP TABLE IF EXISTS `phbkmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `phbkmst` (
  `AC_CD` varchar(7) NOT NULL,
  `LL_NO` varchar(20) NOT NULL,
  `FAX_NO` varchar(20) NOT NULL,
  `MOBILE1` varchar(25) NOT NULL,
  `MOBILE2` varchar(25) NOT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `EMAIL2` varchar(100) DEFAULT NULL,
  `SCHEMESMSSENT` smallint(6) DEFAULT '0',
  PRIMARY KEY (`AC_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `prdt`
--

DROP TABLE IF EXISTS `prdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `prdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `RATE` decimal(10,2) DEFAULT '0.00',
  `TAX_CD` varchar(7) DEFAULT NULL,
  `BASIC_AMT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `AMT` decimal(10,2) DEFAULT '0.00',
  `PUR_TAG_NO` varchar(7) DEFAULT NULL,
  `DISC_RATE` decimal(10,2) DEFAULT '0.00',
  `MRP` decimal(10,2) DEFAULT '0.00',
  `IS_MAIN` decimal(1,0) DEFAULT '1',
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `prhd`
--

DROP TABLE IF EXISTS `prhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `prhd` (
  `REF_NO` varchar(7) NOT NULL,
  `INV_NO` int(11) DEFAULT NULL,
  `V_DATE` date DEFAULT NULL,
  `PMT_DAYS` decimal(3,0) DEFAULT '0',
  `DUE_DATE` date DEFAULT NULL,
  `V_TYPE` decimal(1,0) DEFAULT NULL,
  `PMT_MODE` decimal(1,0) DEFAULT NULL,
  `BILL_DATE` date DEFAULT NULL,
  `BILL_NO` varchar(50) DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `DET_TOT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADJST` decimal(10,2) DEFAULT '0.00',
  `REMARK` varchar(255) DEFAULT NULL,
  `FR_CHG` decimal(10,2) DEFAULT '0.00',
  `NET_AMT` decimal(10,2) DEFAULT '0.00',
  `ADVANCE_AMT` decimal(10,2) DEFAULT '0.00',
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `BRANCH_CD` int(11) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `quotationdt`
--

DROP TABLE IF EXISTS `quotationdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `quotationdt` (
  `ref_no` varchar(10) NOT NULL,
  `sr_no` decimal(3,0) NOT NULL,
  `sr_cd` varchar(7) DEFAULT NULL,
  `QTY` int(11) DEFAULT NULL,
  `disc_per` decimal(10,2) DEFAULT '0.00',
  `rate` decimal(10,2) DEFAULT '0.00',
  `mrp` decimal(10,2) DEFAULT '0.00',
  `amount` decimal(10,2) DEFAULT '0.00',
  PRIMARY KEY (`ref_no`,`sr_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `quotationhd`
--

DROP TABLE IF EXISTS `quotationhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `quotationhd` (
  `ref_no` varchar(10) NOT NULL,
  `inv_no` int(11) DEFAULT NULL,
  `v_date` date DEFAULT NULL,
  `ac_cd` varchar(7) DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `remark` varchar(255) DEFAULT NULL,
  `is_del` decimal(1,0) DEFAULT '0',
  `net_amt` decimal(10,2) DEFAULT '0.00',
  `branch_cd` decimal(1,0) DEFAULT NULL,
  `user_id` decimal(3,0) DEFAULT NULL,
  `edit_no` decimal(2,0) DEFAULT '0',
  `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ref_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `refmst`
--

DROP TABLE IF EXISTS `refmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `refmst` (
  `REF_CD` varchar(7) NOT NULL,
  `REF_NAME` varchar(50) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`REF_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `schememst`
--

DROP TABLE IF EXISTS `schememst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `schememst` (
  `SCHEME_CD` varchar(7) NOT NULL,
  `SCHEME_NAME` varchar(255) DEFAULT NULL,
  `TYPE_CD` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SCHEME_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `seriesmst`
--

DROP TABLE IF EXISTS `seriesmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `seriesmst` (
  `SR_CD` varchar(7) NOT NULL,
  `SR_ALIAS` varchar(50) DEFAULT NULL,
  `SR_NAME` varchar(500) DEFAULT NULL,
  `MODEL_CD` varchar(7) DEFAULT NULL,
  `MEMORY_CD` varchar(7) DEFAULT NULL,
  `COLOUR_CD` varchar(7) DEFAULT NULL,
  `OPB_QTY` decimal(4,0) DEFAULT '0',
  `OPB_VAL` decimal(10,2) DEFAULT '0.00',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(2,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SR_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `smmst`
--

DROP TABLE IF EXISTS `smmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `smmst` (
  `SM_CD` varchar(7) NOT NULL,
  `SM_NAME` varchar(50) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`SM_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `srdt`
--

DROP TABLE IF EXISTS `srdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `srdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `RATE` decimal(10,2) DEFAULT '0.00',
  `TAX_CD` varchar(7) DEFAULT NULL,
  `BASIC_AMT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `AMT` decimal(10,2) DEFAULT '0.00',
  `PUR_TAG_NO` varchar(7) DEFAULT NULL,
  `DISC_RATE` decimal(10,2) DEFAULT '0.00',
  `MRP` decimal(10,2) DEFAULT '0.00',
  `IS_MAIN` decimal(1,0) DEFAULT '1',
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `srhd`
--

DROP TABLE IF EXISTS `srhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `srhd` (
  `REF_NO` varchar(7) NOT NULL,
  `INV_NO` int(11) DEFAULT NULL,
  `V_DATE` date DEFAULT NULL,
  `V_TYPE` decimal(1,0) DEFAULT NULL,
  `PMT_MODE` decimal(1,0) DEFAULT NULL,
  `DUE_DATE` date DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `DET_TOT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADJST` decimal(10,2) DEFAULT '0.00',
  `REMARK` varchar(255) DEFAULT NULL,
  `NET_AMT` decimal(10,2) DEFAULT '0.00',
  `ADVANCE_AMT` decimal(10,2) DEFAULT '0.00',
  `PMT_DAYS` decimal(2,0) DEFAULT '0',
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `BRANCH_CD` int(11) DEFAULT NULL,
  `tax_type` decimal(1,0) DEFAULT '0',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `stkadjdt`
--

DROP TABLE IF EXISTS `stkadjdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `stkadjdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(2,0) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `PUR_TAG_NO` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `stkadjhd`
--

DROP TABLE IF EXISTS `stkadjhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `stkadjhd` (
  `REF_NO` varchar(7) NOT NULL,
  `INV_NO` int(11) DEFAULT NULL,
  `V_DATE` date DEFAULT NULL,
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `REMARK` varchar(255) DEFAULT NULL,
  `branch_cd` decimal(3,0) DEFAULT '1',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `stktrfdt`
--

DROP TABLE IF EXISTS `stktrfdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `stktrfdt` (
  `ref_no` varchar(11) NOT NULL,
  `sr_no` int(11) NOT NULL DEFAULT '0',
  `pur_tag_no` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ref_no`,`sr_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `stktrfhd`
--

DROP TABLE IF EXISTS `stktrfhd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `stktrfhd` (
  `ref_no` varchar(11) NOT NULL,
  `inv_no` decimal(4,0) DEFAULT '0',
  `v_date` date DEFAULT NULL,
  `from_loc` bigint(20) DEFAULT NULL,
  `to_loc` bigint(20) DEFAULT NULL,
  `is_del` decimal(1,0) DEFAULT '0',
  `user_id` bigint(20) DEFAULT NULL,
  `edit_no` decimal(2,0) DEFAULT '0',
  `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approve_by` bigint(20) DEFAULT NULL,
  `approve_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ref_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `stktrfoutdt`
--

DROP TABLE IF EXISTS `stktrfoutdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `stktrfoutdt` (
  `ref_no` varchar(10) NOT NULL,
  `sr_no` int(11) NOT NULL DEFAULT '0',
  `pur_tag_no` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ref_no`,`sr_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `stktrfouthd`
--

DROP TABLE IF EXISTS `stktrfouthd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `stktrfouthd` (
  `ref_no` varchar(10) NOT NULL,
  `inv_no` decimal(10,0) DEFAULT '0',
  `v_date` date DEFAULT NULL,
  `from_loc` bigint(20) DEFAULT NULL,
  `to_loc` bigint(20) DEFAULT NULL,
  `is_del` decimal(1,0) DEFAULT '0',
  `user_id` bigint(20) DEFAULT NULL,
  `edit_no` decimal(2,0) DEFAULT '0',
  `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `approve_by` bigint(20) DEFAULT NULL,
  `approve_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `remark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ref_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tag`
--

DROP TABLE IF EXISTS `tag`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tag` (
  `REF_NO` varchar(7) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `PUR_RATE` decimal(10,2) DEFAULT '0.00',
  `SALE_RATE` decimal(10,2) DEFAULT '0.00',
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `PUR_REF_NO` varchar(7) DEFAULT NULL,
  `SALE_REF_NO` varchar(7) DEFAULT NULL,
  `BASIC_PUR_RATE` decimal(10,2) DEFAULT '0.00',
  `GODOWN` decimal(1,0) DEFAULT '0',
  `MRP` decimal(10,2) DEFAULT '0.00',
  `DISC_RATE` decimal(10,2) DEFAULT '0.00',
  `DISC_RATE_SALES` decimal(10,2) DEFAULT '0.00',
  `BRANCH_CD` decimal(2,0) DEFAULT NULL,
  `IS_MAIN` decimal(1,0) DEFAULT '1',
  `PUR_DATE` date DEFAULT NULL,
  `AC_NAME` varchar(255) DEFAULT NULL,
  `nlc` decimal(10,2) DEFAULT '0.00',
  `old_ref_no` varchar(7) DEFAULT '',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `taxmst`
--

DROP TABLE IF EXISTS `taxmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `taxmst` (
  `TAX_CD` varchar(7) NOT NULL,
  `TAX_NAME` varchar(20) DEFAULT NULL,
  `TAX_PER` decimal(5,2) DEFAULT '0.00',
  `ADD_TAX_PER` decimal(5,2) DEFAULT '0.00',
  `TAX_ON_SALES` decimal(1,0) DEFAULT '1',
  `TAX_AC_CD` varchar(7) DEFAULT NULL,
  `ADD_TAX_AC_CD` varchar(7) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `add_tax_ac_cd1` varchar(7) DEFAULT '',
  PRIMARY KEY (`TAX_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `temp_tag`
--

DROP TABLE IF EXISTS `temp_tag`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `temp_tag` (
  `tag_no` varchar(25) NOT NULL,
  PRIMARY KEY (`tag_no`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `tidmst`
--

DROP TABLE IF EXISTS `tidmst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tidmst` (
  `tid_cd` varchar(7) NOT NULL,
  `tid_name` varchar(255) DEFAULT NULL,
  `user_id` decimal(3,0) DEFAULT NULL,
  `edit_no` decimal(2,0) DEFAULT '0',
  `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tid_cd`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `typemst`
--

DROP TABLE IF EXISTS `typemst`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `typemst` (
  `TYPE_CD` varchar(7) NOT NULL,
  `TYPE_NAME` varchar(50) DEFAULT NULL,
  `EDIT_NO` decimal(3,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TYPE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `vilsdt`
--

DROP TABLE IF EXISTS `vilsdt`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `vilsdt` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(4,0) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `RATE` decimal(10,2) DEFAULT '0.00',
  `TAX_CD` varchar(7) DEFAULT NULL,
  `BASIC_AMT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `AMT` decimal(10,2) DEFAULT '0.00',
  `PUR_TAG_NO` varchar(7) DEFAULT NULL,
  `DISC_RATE` decimal(10,2) DEFAULT '0.00',
  `MRP` decimal(10,2) DEFAULT '0.00',
  `IS_MAIN` decimal(1,0) DEFAULT '1',
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `vilsdtlg`
--

DROP TABLE IF EXISTS `vilsdtlg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `vilsdtlg` (
  `REF_NO` varchar(7) NOT NULL,
  `SR_NO` decimal(4,0) NOT NULL,
  `TAG_NO` varchar(30) DEFAULT NULL,
  `SR_CD` varchar(7) DEFAULT NULL,
  `IMEI_NO` varchar(15) DEFAULT NULL,
  `SERAIL_NO` varchar(25) DEFAULT NULL,
  `QTY` decimal(10,2) DEFAULT '0.00',
  `RATE` decimal(10,2) DEFAULT '0.00',
  `TAX_CD` varchar(7) DEFAULT NULL,
  `BASIC_AMT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `AMT` decimal(10,2) DEFAULT '0.00',
  `PUR_TAG_NO` varchar(7) DEFAULT NULL,
  `DISC_RATE` decimal(10,2) DEFAULT '0.00',
  `MRP` decimal(10,2) DEFAULT '0.00',
  `IS_MAIN` decimal(1,0) DEFAULT '1',
  PRIMARY KEY (`REF_NO`,`SR_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `vilshd`
--

DROP TABLE IF EXISTS `vilshd`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `vilshd` (
  `REF_NO` varchar(7) NOT NULL,
  `INV_NO` int(11) DEFAULT NULL,
  `V_DATE` date DEFAULT NULL,
  `V_TYPE` decimal(1,0) DEFAULT NULL,
  `PMT_MODE` decimal(1,0) DEFAULT NULL,
  `DUE_DATE` date DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `DET_TOT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADJST` decimal(10,2) DEFAULT '0.00',
  `REMARK` varchar(255) DEFAULT NULL,
  `NET_AMT` decimal(10,2) DEFAULT '0.00',
  `BUY_BACK_MODEL` varchar(7) DEFAULT NULL,
  `BUY_BACK_AMT` decimal(10,2) DEFAULT '0.00',
  `PART_NO` varchar(255) DEFAULT NULL,
  `BUY_BACK_IMEI_NO` varchar(25) DEFAULT NULL,
  `ADVANCE_AMT` decimal(10,2) DEFAULT '0.00',
  `INS_CD` varchar(7) DEFAULT NULL,
  `INS_AMT` decimal(10,2) DEFAULT '0.00',
  `BANK_CHARGES` decimal(10,2) DEFAULT '0.00',
  `PMT_DAYS` decimal(2,0) DEFAULT '0',
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `BRANCH_CD` int(11) DEFAULT NULL,
  `DISCOUNT` decimal(10,2) DEFAULT '0.00',
  `ref_cd` varchar(7) DEFAULT NULL,
  `rec_date` date DEFAULT NULL,
  `sm_cd` varchar(7) DEFAULT 'SM00001',
  `scheme_cd` varchar(7) DEFAULT NULL,
  `add_sr_no` decimal(2,0) DEFAULT '1',
  `tax_type` decimal(1,0) DEFAULT '0',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `vilshdlg`
--

DROP TABLE IF EXISTS `vilshdlg`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `vilshdlg` (
  `REF_NO` varchar(7) NOT NULL,
  `INV_NO` int(11) DEFAULT NULL,
  `V_DATE` date DEFAULT NULL,
  `V_TYPE` decimal(1,0) DEFAULT NULL,
  `PMT_MODE` decimal(1,0) DEFAULT NULL,
  `DUE_DATE` date DEFAULT NULL,
  `AC_CD` varchar(7) DEFAULT NULL,
  `DET_TOT` decimal(10,2) DEFAULT '0.00',
  `TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADD_TAX_AMT` decimal(10,2) DEFAULT '0.00',
  `ADJST` decimal(10,2) DEFAULT '0.00',
  `REMARK` varchar(255) DEFAULT NULL,
  `NET_AMT` decimal(10,2) DEFAULT '0.00',
  `BUY_BACK_MODEL` varchar(7) DEFAULT NULL,
  `BUY_BACK_AMT` decimal(10,2) DEFAULT '0.00',
  `PART_NO` varchar(255) DEFAULT NULL,
  `BUY_BACK_IMEI_NO` varchar(25) DEFAULT NULL,
  `ADVANCE_AMT` decimal(10,2) DEFAULT '0.00',
  `INS_CD` varchar(7) DEFAULT NULL,
  `INS_AMT` decimal(10,2) DEFAULT '0.00',
  `BANK_CHARGES` decimal(10,2) DEFAULT '0.00',
  `PMT_DAYS` decimal(2,0) DEFAULT '0',
  `IS_DEL` decimal(1,0) DEFAULT '0',
  `EDIT_NO` decimal(2,0) DEFAULT '0',
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `TIME_STAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INIT_TIMESTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `BRANCH_CD` int(11) DEFAULT NULL,
  `DISCOUNT` decimal(10,2) DEFAULT '0.00',
  `ref_cd` varchar(7) DEFAULT NULL,
  `rec_date` date DEFAULT NULL,
  `sm_cd` varchar(7) DEFAULT 'SM00001',
  `scheme_cd` varchar(7) DEFAULT NULL,
  `add_sr_no` decimal(2,0) DEFAULT '1',
  `tax_type` decimal(1,0) DEFAULT '0',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `visitorbook`
--

DROP TABLE IF EXISTS `visitorbook`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `visitorbook` (
  `REF_NO` varchar(7) NOT NULL,
  `VDATE` date DEFAULT NULL,
  `ac_name` varchar(255) DEFAULT NULL,
  `mobile_no` varchar(25) DEFAULT NULL,
  `USER_ID` decimal(3,0) DEFAULT NULL,
  `model_name` varchar(255) DEFAULT NULL,
  `memory_name` varchar(255) DEFAULT NULL,
  `color_name` varchar(255) DEFAULT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `edit_no` decimal(2,0) DEFAULT '0',
  `time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `attended_by` varchar(7) DEFAULT NULL,
  `follow_up_date` date DEFAULT NULL,
  `rev_ref_no` varchar(7) DEFAULT NULL,
  `branch_cd` decimal(2,0) DEFAULT '1',
  `is_del` decimal(2,0) DEFAULT '0',
  PRIMARY KEY (`REF_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2017-07-05 17:29:45


INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000001', 'SUNDRY DEBTORS', 0, '', 2, 1, 0, 1, '2012-11-06 15:15:06.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000002', 'SUNDRY CREDITORS', 0, '', 2, 0, 0, 1, '2012-11-06 15:15:09.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000003', 'CAPITAL', 0, '', 2, 0, 0, 1, '2012-11-06 15:15:12.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000004', 'ASSETS', 0, '', 2, 1, 0, 1, '2012-11-06 15:15:15.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000005', 'DIRECT EXPENSES', 0, '', 0, 0, 0, 1, '2012-11-06 15:15:18.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000006', 'DIRECT INCOME', 0, '', 0, 1, 0, 1, '2012-11-06 15:15:20.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000007', 'CURRENT LIABILITIES', 0, '', 2, 0, 0, 1, '2012-11-06 15:15:22.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000008', 'CURRENT ASSETS', 0, '', 2, 1, 0, 1, '2012-11-06 15:15:24.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000009', 'INDIRECT EXPENSES', 0, '', 1, 0, 0, 1, '2012-11-06 15:15:27.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000010', 'INDIRECT INCOME', 0, '', 1, 1, 0, 1, '2012-11-06 15:15:32.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000011', 'LOANS & LIABILITIES', 0, '', 2, 0, 0, 1, '2012-11-06 15:15:35.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000012', 'CASH', 0, '', 2, 1, 0, 1, '2013-02-06 12:52:57.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000013', 'BANK', 0, '', 2, 1, 0, 1, '2013-02-06 12:52:57.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000014', 'LOANS & ASSETS', 0, '', 2, 1, 0, 1, '2012-11-06 15:15:35.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000015', 'PURCHASE', 0, '', 0, 0, 0, 1, '2014-11-23 00:40:06.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000016', 'SALES', 0, '', 0, 1, 0, 1, '2014-11-23 00:40:06.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000017', 'SALES RETURN', 0, '', 0, 0, 0, 1, '2014-11-23 00:40:06.0');
INSERT INTO groupmst (GRP_CD, GROUP_NAME, HEAD, HEAD_GRP, ACC_EFF, SIDE, EDIT_NO, USER_ID, TIME_STAMP) VALUES ('G000018', 'PURCHASE RETURN', 0, '', 0, 1, 0, 1, '2014-11-23 00:40:06.0');

